import Foundation

// MARK: - Domain Models

struct AutopilotPlan: Decodable, Hashable {
    let project_name: String?
    let description: String?
    let repo: String?
    let tech_stack: String?
    let milestones: [AutopilotMilestone]?
}

struct AutopilotMilestone: Decodable, Hashable {
    let name: String?
    let goals: [AutopilotGoal]?
}

struct AutopilotGoal: Decodable, Hashable {
    let name: String?
    let mvi_count: Int?
    let human_hours: String?
}

struct AutopilotResult: Decodable, Hashable {
    let project_id: String?
    let wave_id: String?
}

struct AutopilotResponse: Decodable {
    let session_id: String?
    let phase: String?
    let reply: String?
    let plan: AutopilotPlan?
    let result: AutopilotResult?
}

// MARK: - Protocol

protocol AutopilotService {
    func chat(sessionId: String?, message: String, action: String) async throws -> AutopilotResponse
}

// MARK: - InMemory Implementation

final class InMemoryAutopilotService: AutopilotService {
    private var turnCount: Int = 0

    func chat(sessionId: String?, message: String, action: String) async throws -> AutopilotResponse {
        try await Task.sleep(for: .milliseconds(600))

        if action == "launch" {
            return AutopilotResponse(
                session_id: sessionId ?? UUID().uuidString,
                phase: "executing",
                reply: "Your project is being set up. Monarch is generating documents and launching the first wave.",
                plan: nil,
                result: AutopilotResult(project_id: "preview-project", wave_id: nil)
            )
        }

        turnCount += 1
        if turnCount >= 2 {
            let plan = AutopilotPlan(
                project_name: "My App",
                description: "A demo project generated by Monarch.",
                repo: "org/my-app",
                tech_stack: "Node.js, DynamoDB",
                milestones: [
                    AutopilotMilestone(
                        name: "Foundation",
                        goals: [
                            AutopilotGoal(name: "Project setup", mvi_count: 2, human_hours: "~4h"),
                            AutopilotGoal(name: "Core API", mvi_count: 3, human_hours: "~8h")
                        ]
                    )
                ]
            )
            return AutopilotResponse(
                session_id: sessionId ?? UUID().uuidString,
                phase: "proposed",
                reply: "Got it. Here's my plan:\n\nTap 'Review Plan' to see the full breakdown.",
                plan: plan,
                result: nil
            )
        }

        return AutopilotResponse(
            session_id: sessionId ?? UUID().uuidString,
            phase: "gathering",
            reply: "Great idea! A couple of quick questions:\n1. Should I create a new GitHub repo or use an existing one?\n2. What's your preferred tech stack?",
            plan: nil,
            result: nil
        )
    }
}

// MARK: - API Implementation

final class APIAutopilotService: AutopilotService {
    private let client: APIClient

    init(client: APIClient) {
        self.client = client
    }

    func chat(sessionId: String?, message: String, action: String) async throws -> AutopilotResponse {
        struct Body: Encodable {
            let session_id: String?
            let message: String
            let action: String
        }
        return try await client.post(
            "/projects/autopilot/chat",
            body: Body(session_id: sessionId, message: message, action: action)
        )
    }
}
