"""Git workflow — clone, branch, PR lifecycle for agent executions.

This module bridges Murder ↔ GitOps:
1. Clone (or reuse) the target repository
2. Create a feature branch for the task
3. After agents complete, push and create PR
4. Update GitHub issue with status/links
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path
from typing import Optional

from cawnex_git_ops import GitHubAPI

logger = logging.getLogger("cawnex.git_workflow")

# Base directory for all cloned repos and worktrees
REPOS_BASE = Path.home() / ".cawnex" / "repos"
NESTS_BASE = Path.home() / ".cawnex" / "nests"


def ensure_repo_cloned(repo_full_name: str, github_token: str) -> Path:
    """Clone or update a repository. Returns the path to the local clone.

    Uses bare-ish clone with a single main branch to keep disk usage low.
    Repos are cached in ~/.cawnex/repos/{owner}/{repo}/.
    """
    REPOS_BASE.mkdir(parents=True, exist_ok=True)
    repo_dir = REPOS_BASE / repo_full_name.replace("/", "-")

    clone_url = f"https://x-access-token:{github_token}@github.com/{repo_full_name}.git"

    if repo_dir.exists():
        # Update existing clone
        logger.info(f"  📥 Updating {repo_full_name}...")
        _run_git(["fetch", "origin"], cwd=repo_dir)
        _run_git(["reset", "--hard", "origin/main"], cwd=repo_dir)
    else:
        # Fresh clone
        logger.info(f"  📥 Cloning {repo_full_name}...")
        _run_git(["clone", "--depth", "50", clone_url, str(repo_dir)])

    return repo_dir


def create_task_branch(
    repo_dir: Path,
    task_id: int,
    issue_number: int | None = None,
) -> tuple[Path, str]:
    """Create an isolated working directory with a feature branch.

    Returns (workspace_path, branch_name).
    """
    NESTS_BASE.mkdir(parents=True, exist_ok=True)

    # Branch naming: cawnex/issue-{n} or cawnex/task-{id}
    if issue_number:
        branch_name = f"cawnex/issue-{issue_number}"
    else:
        branch_name = f"cawnex/task-{task_id}"

    nest_dir = NESTS_BASE / branch_name.replace("/", "-")

    # Clean up stale nest
    if nest_dir.exists():
        shutil.rmtree(nest_dir)

    # Copy repo (cheaper than worktree for shallow clones)
    shutil.copytree(repo_dir, nest_dir)

    # Create and checkout the feature branch
    _run_git(["checkout", "-B", branch_name], cwd=nest_dir)

    # Configure git identity for commits
    _run_git(["config", "user.email", "cawnex@cawnex.ai"], cwd=nest_dir)
    _run_git(["config", "user.name", "Cawnex"], cwd=nest_dir)

    logger.info(f"  🪹 Nest created: {nest_dir} (branch: {branch_name})")
    return nest_dir, branch_name


def commit_and_push(
    workspace: Path,
    branch_name: str,
    commit_message: str,
    github_token: str,
    repo_full_name: str,
) -> bool:
    """Stage all changes, commit, and push the branch.

    Returns True if there were changes to push.
    """
    # Check for changes
    status = _run_git(["status", "--porcelain"], cwd=workspace)
    if not status.strip():
        logger.info("  📭 No changes to commit")
        return False

    # Stage all
    _run_git(["add", "-A"], cwd=workspace)

    # Commit
    _run_git(["commit", "-m", commit_message], cwd=workspace)

    # Set push URL with token
    push_url = f"https://x-access-token:{github_token}@github.com/{repo_full_name}.git"
    _run_git(["remote", "set-url", "origin", push_url], cwd=workspace)

    # Push (force in case branch existed before)
    _run_git(["push", "-f", "origin", branch_name], cwd=workspace)

    logger.info(f"  📤 Pushed branch {branch_name}")
    return True


async def create_pull_request(
    github: GitHubAPI,
    repo_full_name: str,
    branch_name: str,
    task_title: str,
    task_description: str | None,
    issue_number: int | None,
    step_summaries: list[dict],
) -> dict:
    """Create a PR with a summary of what the agents did."""
    # Build PR body
    body_parts = []

    if issue_number:
        body_parts.append(f"Closes #{issue_number}\n")

    body_parts.append("## 🐦‍⬛ Cawnex Automated PR\n")

    if task_description:
        body_parts.append(f"### Task\n{task_description}\n")

    body_parts.append("### Agent Execution Summary\n")
    for summary in step_summaries:
        status = "✅" if summary.get("success") else "❌"
        body_parts.append(
            f"- {status} **{summary['agent']}** — {summary['step']} "
            f"({summary.get('duration', 0):.1f}s, {summary.get('tool_calls', 0)} tool calls)"
        )
        if summary.get("output_preview"):
            body_parts.append(f"  > {summary['output_preview'][:200]}")
    body_parts.append("")

    body_parts.append("---\n*Generated by [Cawnex](https://cawnex.ai) — Coordinated Intelligence*")

    body = "\n".join(body_parts)

    pr = await github.create_pr(
        repo_full_name,
        title=f"🐦‍⬛ {task_title}",
        body=body,
        head=branch_name,
        base="main",
        draft=False,
    )

    logger.info(f"  🔀 PR created: #{pr['number']} — {pr['html_url']}")
    return pr


async def update_issue_status(
    github: GitHubAPI,
    repo_full_name: str,
    issue_number: int,
    labels: list[str] | None = None,
    comment: str | None = None,
) -> None:
    """Update GitHub issue with labels and/or a comment."""
    try:
        if labels:
            await github.add_label(repo_full_name, issue_number, labels)
        if comment:
            await github.add_pr_comment(repo_full_name, issue_number, comment)
    except Exception as e:
        logger.warning(f"  ⚠️ Failed to update issue #{issue_number}: {e}")


def cleanup_nest(workspace: Path) -> None:
    """Remove the workspace after execution."""
    try:
        if workspace.exists() and str(NESTS_BASE) in str(workspace):
            shutil.rmtree(workspace)
            logger.info(f"  🧹 Cleaned up nest: {workspace}")
    except Exception as e:
        logger.warning(f"  ⚠️ Cleanup failed: {e}")


def _run_git(args: list[str], cwd: Path | None = None) -> str:
    """Run a git command, return stdout."""
    result = subprocess.run(
        ["git"] + args,
        cwd=cwd,
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0:
        # Don't log token URLs
        safe_args = [a if "x-access-token" not in str(a) else "[REDACTED]" for a in args]
        logger.debug(f"  git {' '.join(safe_args)}: {result.stderr.strip()}")
    return result.stdout
